networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
  
volumes:  
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}
services:


### PHP-FPM ##############################################
    frankenphp:
      build:
        context: ./frankenphp
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - BASE_IMAGE_TAG_PREFIX=${FRANKENPHP_BASE_IMAGE_TAG_PREFIX}
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - LARADOCK_PHALCON_VERSION=${PHALCON_VERSION}
          - INSTALL_BZ2=${FRANKENPHP_INSTALL_BZ2}
          - INSTALL_ENCHANT=${FRANKENPHP_INSTALL_ENCHANT}
          - INSTALL_GMP=${FRANKENPHP_INSTALL_GMP}
          - INSTALL_GNUPG=${FRANKENPHP_INSTALL_GNUPG}
          - INSTALL_XDEBUG=${FRANKENPHP_INSTALL_XDEBUG}
          - XDEBUG_PORT=${FRANKENPHP_XDEBUG_PORT}
          - INSTALL_PCOV=${FRANKENPHP_INSTALL_PCOV}
          - INSTALL_PHPDBG=${FRANKENPHP_INSTALL_PHPDBG}
          - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE}
          - INSTALL_SSH2=${FRANKENPHP_INSTALL_SSH2}
          - INSTALL_SOAP=${FRANKENPHP_INSTALL_SOAP}
          - INSTALL_XSL=${FRANKENPHP_INSTALL_XSL}
          - INSTALL_SMB=${FRANKENPHP_INSTALL_SMB}
          - INSTALL_IMAP=${FRANKENPHP_INSTALL_IMAP}
          - INSTALL_MONGO=${FRANKENPHP_INSTALL_MONGO}
          - INSTALL_AMQP=${FRANKENPHP_INSTALL_AMQP}
          - INSTALL_CASSANDRA=${FRANKENPHP_INSTALL_CASSANDRA}
          - INSTALL_ZMQ=${FRANKENPHP_INSTALL_ZMQ}
          - INSTALL_GEARMAN=${FRANKENPHP_INSTALL_GEARMAN}
          - INSTALL_MSSQL=${FRANKENPHP_INSTALL_MSSQL}
          - INSTALL_BCMATH=${FRANKENPHP_INSTALL_BCMATH}
          - INSTALL_PHPREDIS=${FRANKENPHP_INSTALL_PHPREDIS}
          - INSTALL_MEMCACHED=${FRANKENPHP_INSTALL_MEMCACHED}
          - INSTALL_OPCACHE=${FRANKENPHP_INSTALL_OPCACHE}
          - INSTALL_EXIF=${FRANKENPHP_INSTALL_EXIF}
          - INSTALL_AEROSPIKE=${FRANKENPHP_INSTALL_AEROSPIKE}
          - INSTALL_OCI8=${FRANKENPHP_INSTALL_OCI8}
          - INSTALL_MYSQLI=${FRANKENPHP_INSTALL_MYSQLI}
          - INSTALL_PGSQL=${FRANKENPHP_INSTALL_PGSQL}
          - INSTALL_PG_CLIENT=${FRANKENPHP_INSTALL_PG_CLIENT}
          - PG_CLIENT_VERSION=${POSTGRES_CLIENT_VERSION}
          - INSTALL_POSTGIS=${FRANKENPHP_INSTALL_POSTGIS}
          - INSTALL_INTL=${FRANKENPHP_INSTALL_INTL}
          - INSTALL_GHOSTSCRIPT=${FRANKENPHP_INSTALL_GHOSTSCRIPT}
          - INSTALL_LDAP=${FRANKENPHP_INSTALL_LDAP}
          - INSTALL_PHALCON=${FRANKENPHP_INSTALL_PHALCON}
          - INSTALL_SWOOLE=${FRANKENPHP_INSTALL_SWOOLE}
          - INSTALL_TAINT=${FRANKENPHP_INSTALL_TAINT}
          - INSTALL_IMAGE_OPTIMIZERS=${FRANKENPHP_INSTALL_IMAGE_OPTIMIZERS}
          - INSTALL_IMAGEMAGICK=${FRANKENPHP_INSTALL_IMAGEMAGICK}
          - INSTALL_CALENDAR=${FRANKENPHP_INSTALL_CALENDAR}
          - INSTALL_XLSWRITER=${FRANKENPHP_INSTALL_XLSWRITER}
          - INSTALL_FAKETIME=${FRANKENPHP_INSTALL_FAKETIME}
          - INSTALL_IONCUBE=${FRANKENPHP_INSTALL_IONCUBE}
          - INSTALL_APCU=${FRANKENPHP_INSTALL_APCU}
          - INSTALL_CACHETOOL=${FRANKENPHP_INSTALL_CACHETOOL}
          - INSTALL_YAML=${FRANKENPHP_INSTALL_YAML}
          - INSTALL_RDKAFKA=${FRANKENPHP_INSTALL_RDKAFKA}
          - INSTALL_GETTEXT=${FRANKENPHP_INSTALL_GETTEXT}
          - INSTALL_ADDITIONAL_LOCALES=${FRANKENPHP_INSTALL_ADDITIONAL_LOCALES}
          - INSTALL_MYSQL_CLIENT=${FRANKENPHP_INSTALL_MYSQL_CLIENT}
          - INSTALL_PING=${FRANKENPHP_INSTALL_PING}
          - INSTALL_SSHPASS=${FRANKENPHP_INSTALL_SSHPASS}
          - INSTALL_MAILPARSE=${FRANKENPHP_INSTALL_MAILPARSE}
          - INSTALL_PCNTL=${FRANKENPHP_INSTALL_PCNTL}
          - ADDITIONAL_LOCALES=${FRANKENPHP_ADDITIONAL_LOCALES}
          - INSTALL_FFMPEG=${FRANKENPHP_FFMPEG}
          - INSTALL_AUDIOWAVEFORM=${FRANKENPHP_AUDIOWAVEFORM}
          - INSTALL_WKHTMLTOPDF=${FRANKENPHP_INSTALL_WKHTMLTOPDF}
          - WKHTMLTOPDF_VERSION=${FRANKENPHP_WKHTMLTOPDF_VERSION}
          - INSTALL_XHPROF=${FRANKENPHP_INSTALL_XHPROF}
          - INSTALL_XMLRPC=${FRANKENPHP_INSTALL_XMLRPC}
          - INSTALL_PHPDECIMAL=${FRANKENPHP_INSTALL_PHPDECIMAL}
          - INSTALL_ZOOKEEPER=${FRANKENPHP_INSTALL_ZOOKEEPER}
          - INSTALL_SSDB=${FRANKENPHP_INSTALL_SSDB}
          - INSTALL_TRADER=${FRANKENPHP_INSTALL_TRADER}
          - INSTALL_EVENT=${FRANKENPHP_INSTALL_EVENT}
          - LEGACY_OPENSSL=${PHP_LEGACY_OPENSSL}
          - DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL=${PHP_DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL}
          - DOWNGRADE_OPENSSL_TLS_VERSION=${PHP_DOWNGRADE_OPENSSL_TLS_VERSION}
          - PUID=${FRANKENPHP_PUID}
          - PGID=${FRANKENPHP_PGID}
          - IMAGEMAGICK_VERSION=${FRANKENPHP_IMAGEMAGICK_VERSION}
          - LOCALE=${FRANKENPHP_DEFAULT_LOCALE}
          - NEW_RELIC=${FRANKENPHP_NEW_RELIC}
          - NEW_RELIC_KEY=${FRANKENPHP_NEW_RELIC_KEY}
          - NEW_RELIC_APP_NAME=${FRANKENPHP_NEW_RELIC_APP_NAME}
          - INSTALL_DOCKER_CLIENT=${FRANKENPHP_INSTALL_DOCKER_CLIENT}
          - INSTALL_DNSUTILS=${FRANKENPHP_INSTALL_DNSUTILS}
          - INSTALL_POPPLER_UTILS=${FRANKENPHP_INSTALL_POPPLER_UTILS}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        #- ./php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        #- docker-in-docker:/certs/client      
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"  
      environment:
        - SERVER_NAME=localhost
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
        - FAKETIME=${PHP_FPM_FAKETIME}
      depends_on:
        - workspace
      networks:
        - backend
      links:
        - docker-in-docker                
      ports:
        - "80:80" # HTTP
        - "443:443" # HTTPS
        - "443:443/udp" # HTTP/3


### Workspace Utilities ##################################
    workspace:
      build:
        context: ./workspace
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - SHELL_OH_MY_ZSH=${SHELL_OH_MY_ZSH}
          - SHELL_OH_MY_ZSH_AUTOSUGESTIONS=${SHELL_OH_MY_ZSH_AUTOSUGESTIONS}
          - SHELL_OH_MY_ZSH_ALIASES=${SHELL_OH_MY_ZSH_ALIASES}
          - BASE_IMAGE_TAG_PREFIX=${WORKSPACE_BASE_IMAGE_TAG_PREFIX}
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - LARADOCK_PHALCON_VERSION=${PHALCON_VERSION}
          - INSTALL_SUBVERSION=${WORKSPACE_INSTALL_SUBVERSION}
          - INSTALL_BZ2=${WORKSPACE_INSTALL_BZ2}
          - INSTALL_GMP=${WORKSPACE_INSTALL_GMP}
          - INSTALL_GNUPG=${WORKSPACE_INSTALL_GNUPG}
          - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
          - XDEBUG_PORT=${WORKSPACE_XDEBUG_PORT}
          - INSTALL_PCOV=${WORKSPACE_INSTALL_PCOV}
          - INSTALL_PHPDBG=${WORKSPACE_INSTALL_PHPDBG}
          - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE}
          - INSTALL_SSH2=${WORKSPACE_INSTALL_SSH2}
          - INSTALL_SOAP=${WORKSPACE_INSTALL_SOAP}
          - INSTALL_XSL=${WORKSPACE_INSTALL_XSL}
          - INSTALL_LDAP=${WORKSPACE_INSTALL_LDAP}
          - INSTALL_SMB=${WORKSPACE_INSTALL_SMB}
          - INSTALL_IMAP=${WORKSPACE_INSTALL_IMAP}
          - INSTALL_MONGO=${WORKSPACE_INSTALL_MONGO}
          - INSTALL_AMQP=${WORKSPACE_INSTALL_AMQP}
          - INSTALL_CASSANDRA=${WORKSPACE_INSTALL_CASSANDRA}
          - INSTALL_ZMQ=${WORKSPACE_INSTALL_ZMQ}
          - INSTALL_GEARMAN=${WORKSPACE_INSTALL_GEARMAN}
          - INSTALL_PHPREDIS=${WORKSPACE_INSTALL_PHPREDIS}
          - INSTALL_MSSQL=${WORKSPACE_INSTALL_MSSQL}
          - NVM_NODEJS_ORG_MIRROR=${WORKSPACE_NVM_NODEJS_ORG_MIRROR}
          - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
          - NPM_REGISTRY=${WORKSPACE_NPM_REGISTRY}
          - NPM_FETCH_RETRIES=${WORKSPACE_NPM_FETCH_RETRIES}
          - NPM_FETCH_RETRY_FACTOR=${WORKSPACE_NPM_FETCH_RETRY_FACTOR}
          - NPM_FETCH_RETRY_MINTIMEOUT=${WORKSPACE_NPM_FETCH_RETRY_MINTIMEOUT}
          - NPM_FETCH_RETRY_MAXTIMEOUT=${WORKSPACE_NPM_FETCH_RETRY_MAXTIMEOUT}
          - INSTALL_PNPM=${WORKSPACE_INSTALL_PNPM}
          - INSTALL_YARN=${WORKSPACE_INSTALL_YARN}
          - INSTALL_NPM_GULP=${WORKSPACE_INSTALL_NPM_GULP}
          - INSTALL_NPM_BOWER=${WORKSPACE_INSTALL_NPM_BOWER}
          - INSTALL_NPM_VUE_CLI=${WORKSPACE_INSTALL_NPM_VUE_CLI}
          - INSTALL_NPM_ANGULAR_CLI=${WORKSPACE_INSTALL_NPM_ANGULAR_CLI}
          - INSTALL_NPM_CHECK_UPDATES_CLI=${WORKSPACE_INSTALL_NPM_CHECK_UPDATES_CLI}
          - INSTALL_DRUSH=${WORKSPACE_INSTALL_DRUSH}
          - INSTALL_WP_CLI=${WORKSPACE_INSTALL_WP_CLI}
          - INSTALL_DRUPAL_CONSOLE=${WORKSPACE_INSTALL_DRUPAL_CONSOLE}
          - INSTALL_AEROSPIKE=${WORKSPACE_INSTALL_AEROSPIKE}
          - INSTALL_OCI8=${WORKSPACE_INSTALL_OCI8}
          - INSTALL_V8JS=${WORKSPACE_INSTALL_V8JS}
          - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
          - COMPOSER_VERSION=${WORKSPACE_COMPOSER_VERSION}
          - COMPOSER_AUTH_JSON=${WORKSPACE_COMPOSER_AUTH_JSON}
          - COMPOSER_REPO_PACKAGIST=${WORKSPACE_COMPOSER_REPO_PACKAGIST}
          - INSTALL_WORKSPACE_SSH=${WORKSPACE_INSTALL_WORKSPACE_SSH}
          - INSTALL_LARAVEL_ENVOY=${WORKSPACE_INSTALL_LARAVEL_ENVOY}
          - INSTALL_LARAVEL_INSTALLER=${WORKSPACE_INSTALL_LARAVEL_INSTALLER}
          - INSTALL_XLSWRITER=${WORKSPACE_INSTALL_XLSWRITER}
          - INSTALL_DEPLOYER=${WORKSPACE_INSTALL_DEPLOYER}
          - INSTALL_PRESTISSIMO=${WORKSPACE_INSTALL_PRESTISSIMO}
          - INSTALL_LINUXBREW=${WORKSPACE_INSTALL_LINUXBREW}
          - INSTALL_MC=${WORKSPACE_INSTALL_MC}
          - INSTALL_SYMFONY=${WORKSPACE_INSTALL_SYMFONY}
          - INSTALL_PYTHON=${WORKSPACE_INSTALL_PYTHON}
          - INSTALL_PYTHON3=${WORKSPACE_INSTALL_PYTHON3}
          - INSTALL_IMAGE_OPTIMIZERS=${WORKSPACE_INSTALL_IMAGE_OPTIMIZERS}
          - INSTALL_IMAGEMAGICK=${WORKSPACE_INSTALL_IMAGEMAGICK}
          - INSTALL_TERRAFORM=${WORKSPACE_INSTALL_TERRAFORM}
          - INSTALL_DUSK_DEPS=${WORKSPACE_INSTALL_DUSK_DEPS}
          - INSTALL_PG_CLIENT=${WORKSPACE_INSTALL_PG_CLIENT}
          - PG_CLIENT_VERSION=${POSTGRES_CLIENT_VERSION}
          - INSTALL_PHALCON=${WORKSPACE_INSTALL_PHALCON}
          - INSTALL_SWOOLE=${WORKSPACE_INSTALL_SWOOLE}
          - INSTALL_TAINT=${WORKSPACE_INSTALL_TAINT}
          - INSTALL_LIBPNG=${WORKSPACE_INSTALL_LIBPNG}
          - INSTALL_GRAPHVIZ=${WORKSPACE_INSTALL_GRAPHVIZ}
          - INSTALL_IONCUBE=${WORKSPACE_INSTALL_IONCUBE}
          - INSTALL_APCU=${WORKSPACE_INSTALL_APCU}
          - INSTALL_MYSQL_CLIENT=${WORKSPACE_INSTALL_MYSQL_CLIENT}
          - INSTALL_PING=${WORKSPACE_INSTALL_PING}
          - INSTALL_SSHPASS=${WORKSPACE_INSTALL_SSHPASS}
          - INSTALL_INOTIFY=${WORKSPACE_INSTALL_INOTIFY}
          - INSTALL_FSWATCH=${WORKSPACE_INSTALL_FSWATCH}
          - INSTALL_AST=${WORKSPACE_INSTALL_AST}
          - INSTALL_YAML=${WORKSPACE_INSTALL_YAML}
          - INSTALL_RDKAFKA=${WORKSPACE_INSTALL_RDKAFKA}
          - INSTALL_MAILPARSE=${WORKSPACE_INSTALL_MAILPARSE}
          - INSTALL_GIT_PROMPT=${WORKSPACE_INSTALL_GIT_PROMPT}
          - INSTALL_XMLRPC=${WORKSPACE_INSTALL_XMLRPC}
          - PUID=${WORKSPACE_PUID}
          - PGID=${WORKSPACE_PGID}
          - CHROME_DRIVER_VERSION=${WORKSPACE_CHROME_DRIVER_VERSION}
          - NODE_VERSION=${WORKSPACE_NODE_VERSION}
          - YARN_VERSION=${WORKSPACE_YARN_VERSION}
          - DRUSH_VERSION=${WORKSPACE_DRUSH_VERSION}
          - AST_VERSION=${WORKSPACE_AST_VERSION}
          - IMAGEMAGICK_VERSION=${WORKSPACE_IMAGEMAGICK_VERSION}
          - TZ=${WORKSPACE_TIMEZONE}
          - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
          - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
          - INSTALL_POWERLINE=${WORKSPACE_INSTALL_POWERLINE}
          - INSTALL_SUPERVISOR=${WORKSPACE_INSTALL_SUPERVISOR}
          - INSTALL_FFMPEG=${WORKSPACE_INSTALL_FFMPEG}
          - INSTALL_AUDIOWAVEFORM=${WORKSPACE_INSTALL_AUDIOWAVEFORM}
          - INSTALL_WKHTMLTOPDF=${WORKSPACE_INSTALL_WKHTMLTOPDF}
          - WKHTMLTOPDF_VERSION=${WORKSPACE_WKHTMLTOPDF_VERSION}
          - INSTALL_GNU_PARALLEL=${WORKSPACE_INSTALL_GNU_PARALLEL}
          - INSTALL_LNAV=${WORKSPACE_INSTALL_LNAV}
          - INSTALL_PROTOC=${WORKSPACE_INSTALL_PROTOC}
          - INSTALL_PHPDECIMAL=${WORKSPACE_INSTALL_PHPDECIMAL}
          - INSTALL_ZOOKEEPER=${WORKSPACE_INSTALL_ZOOKEEPER}
          - INSTALL_SSDB=${WORKSPACE_INSTALL_SSDB}
          - INSTALL_TRADER=${WORKSPACE_INSTALL_TRADER}
          - PROTOC_VERSION=${WORKSPACE_PROTOC_VERSION}
          - INSTALL_DOCKER_CLIENT=${WORKSPACE_INSTALL_DOCKER_CLIENT}
          - INSTALL_MEMCACHED=${WORKSPACE_INSTALL_MEMCACHED}
          - INSTALL_EVENT=${WORKSPACE_INSTALL_EVENT}
          - INSTALL_DNSUTILS=${WORKSPACE_INSTALL_DNSUTILS}
          - INSTALL_POPPLER_UTILS=${WORKSPACE_INSTALL_POPPLER_UTILS}
          - INSTALL_JDK=${WORKSPACE_INSTALL_JDK}
          - INSTALL_GITHUB_CLI=${WORKSPACE_INSTALL_GITHUB_CLI}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - docker-in-docker:/certs/client
        - ./php-worker/supervisord.d:/etc/supervisord.d
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      ports:
        - "${WORKSPACE_SSH_PORT}:22"
        - "${WORKSPACE_BROWSERSYNC_HOST_PORT}:3000"
        - "${WORKSPACE_BROWSERSYNC_UI_HOST_PORT}:3001"
        - "${WORKSPACE_VUE_CLI_SERVE_HOST_PORT}:8080"
        - "${WORKSPACE_VUE_CLI_UI_HOST_PORT}:8000"
        - "${WORKSPACE_ANGULAR_CLI_SERVE_HOST_PORT}:4200"
        - "${WORKSPACE_VITE_PORT}:5173"
      tty: true
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
        - CHOKIDAR_USEPOLLING=true
      networks:
        - frontend
        - backend
      links:
        - docker-in-docker

### Docker-in-Docker ################################################
    docker-in-docker:
      image: docker:20.10-dind
      environment:
        DOCKER_TLS_SAN: DNS:docker-in-docker
      privileged: true
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - docker-in-docker:/certs/client
      expose:
        - 2375
      networks:
        - backend
